# **Q1**

In [ ]:
import numpy as np

In [ ]:
arr1=np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# **Q2**

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

# **Q3**

In [ ]:
arr2=np.arange(2,20,2)

In [ ]:
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# **Q4**

In [ ]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [ ]:
arr2=np.array([4,5,6])
arr2

array([4, 5, 6])

In [ ]:
arr3=arr1*arr2

In [ ]:
arr3

array([ 4, 10, 18])

In [ ]:
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
arr3=arr1+arr2
arr3


array([5, 7, 9])

In [ ]:
arr3=arr1/arr2
arr3



array([0.25, 0.4 , 0.5 ])

# **Q5**

In [ ]:
arr4=np.random.rand(100)

In [ ]:
arr4

array([0.45905074, 0.23209494, 0.04552868, 0.94325573, 0.17473595,
       0.48300618, 0.81055829, 0.17224799, 0.63227949, 0.04130275,
       0.53341218, 0.22090214, 0.65159985, 0.36438848, 0.50801646,
       0.84835496, 0.87510464, 0.09013992, 0.08732047, 0.18199924,
       0.27656103, 0.92748614, 0.21658485, 0.51120071, 0.83284195,
       0.49826904, 0.90761411, 0.76527447, 0.25587203, 0.0610631 ,
       0.43438748, 0.93338306, 0.71959154, 0.87936527, 0.74973568,
       0.30897754, 0.21709336, 0.41507529, 0.93057339, 0.25709859,
       0.11849665, 0.85979593, 0.21233412, 0.06561339, 0.06002853,
       0.18513502, 0.19257089, 0.49258702, 0.74328042, 0.93906504,
       0.59957685, 0.13597459, 0.41934324, 0.76225041, 0.17963632,
       0.93019864, 0.09780784, 0.19276358, 0.04414326, 0.85048419,
       0.95794741, 0.64244834, 0.88891993, 0.68683272, 0.59473741,
       0.14167122, 0.53071694, 0.06815444, 0.35446623, 0.13956461,
       0.59893054, 0.12850047, 0.71899489, 0.75256403, 0.34434

In [ ]:
arr4.mean()

0.4839736104852721

# **Q6**

In [ ]:
arr5=np.random.randint(0,20,12)

In [ ]:
arr5

array([ 5,  7, 12,  6,  0,  1, 12, 17, 17, 17,  2, 17])

In [ ]:
arr5=np.random.randint(0,20,12).reshape(3,4)

In [ ]:
arr5

array([[ 4,  8,  9,  8],
       [ 0, 14,  4, 19],
       [12, 10, 11, 15]])

# **Q7**

In [ ]:
arr6=np.array([1,2,3,4,5])
arr6

array([1, 2, 3, 4, 5])

In [ ]:
np.square(arr6)

array([ 1,  4,  9, 16, 25])

# **Q8**

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Q9**


In [ ]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b=np.array([4,5,6])
b

array([4, 5, 6])

In [ ]:
a.dot(b)

32

## **Q10**

In [ ]:
arr5

array([[ 4,  8,  9,  8],
       [ 0, 14,  4, 19],
       [12, 10, 11, 15]])

In [ ]:
arr5.argmax()

7

In [ ]:
arr5.argmin()

4

In [ ]:
a

# **Q11**


In [ ]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.concatenate([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.concatenate([a,b],axis=1)

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

# **Q12**

In [4]:
import numpy as np
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("sum of each colomn is",np.sum(arr,axis=0))
print("sum of each row is",np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each colomn is [28 32 36 40]
sum of each row is [10 26 42 58]


# **Q13**

In [7]:
a=np.array([[4,9],[5,8],[1,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print('The common elements betweena nad b are',c)

The common elements betweena nad b are [5 7 9]


# **Q14**

In [8]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

# **Q15**

In [10]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([  2,   2,   2,   2,   3,   3,   4,   5,   6,   7,   7,   9,   9,
         9,  10,  11,  11,  12,  12,  12,  13,  14,  17,  20,  22,  23,
        24,  24,  24,  25,  25,  26,  27,  28,  29,  31,  32,  33,  34,
        35,  37,  39,  40,  41,  41,  43,  43,  47,  47,  48,  48,  49,
        50,  50,  53,  54,  56,  56,  56,  57,  57,  59,  60,  62,  62,
        63,  63,  66,  67,  68,  68,  69,  69,  69,  71,  72,  72,  72,
        73,  73,  75,  75,  78,  79,  80,  80,  81,  84,  85,  85,  87,
        88,  90,  91,  91,  94,  97,  97, 100, 100])

# **Q16**

In [11]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print('The element-wise absolute difference between the two arrays is',c)


The element-wise absolute difference between the two arrays is [5 6 7 8 9]


# **Q17**

In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print('first rows is\n',firstrow)
print('last column is\n',lastcol)

first rows is
 [1 2 3]
last column is
 [[3]
 [6]
 [9]]


# **Q18**

In [14]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


# **Q19**

In [15]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('original array is\n',arr)
print('central 2*2 elements include\n',x)

original array is
 [[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2*2 elements include
 [[38 40]
 [50 52]]


# **Q20**

In [16]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])